name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Stack
      run: stack build
    - name: Copy Executable
      run: cp $(stack path --dist-dir)/build/mksense/mksense .

    - uses: actions/upload-artifact@v1
      with:
        name: mksense
        path: mksense
